---
- name: Reboot Windows device
  hosts: all
  gather_facts: false
  tasks:
    - name: Restart Windows
      win_reboot:
        reboot_timeout: 300
        reboot_msg: "Reboot initiated by Ansible"
