- name: updates
  hosts: jhbansiblewinserv
  connection: winrm

  tasks:
    win_updates:
      category_names:
        - CriticalUpdates
        - SecurityUpdates
    reboot: yes
    reboot_timeout: 900
