---
- name: Reboot Windows device
  hosts: windows_hosts
  gather_facts: false
  tasks:
    - name: Restart Windows
      win_reboot:
        reboot_timeout: 30
        reboot_msg: "Reboot initiated by Ansible"
