---
- name: Reboot Windows Server
  hosts: windows_hosts
  gather_facts: false

  tasks:
    - name: Reboot the server
      win_reboot:
        reboot_timeout: 600
        msg: "Reboot initiated by Ansible"
      become: true
