- name: Run Updates on Directory Servers then wait 15 mins
  hosts: all
  connection: winrm

  tasks:
    win_updates:
      category_names:
        - CriticalUpdates
        - SecurityUpdates
    reboot: yes
    reboot_timeout: 900
