- hosts: jhbansibleWINserv

  become: true
  tasks:
    - name: updates
        connection: winrm

  tasks:
    win_updates:
      category_names:
        - CriticalUpdates
        - SecurityUpdates
    reboot: yes
    reboot_timeout: 900
