---
- name: Install Windows Updates
  hosts: all
  gather_facts: false
  tasks:
    - name: Check for Windows updates
      win_updates:
        category_names: SecurityUpdates,Updates
        state: searched
      register: windows_updates

    - name: Install Windows updates
      win_updates:
        category_names: SecurityUpdates,Updates
        state: installed
      when: windows_updates.updates | length > 0
